dist: trusty
sudo: required
addons:
    postgresql: "9.5"
before_script:
  - sudo psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'sabha123'"
  - sudo psql -U postgres -c 'CREATE DATABASE tournaments'

language:
    java
jdk:
    - oraclejdk8
env:
    - TERM=dumb
script:
    - gradle build
after_success:
    deploy:
      skip_cleanup: true
      provider: elasticbeanstalk
      access-key-id: AKIAIV4EWOC3ZDFD2NUA
      secret-access-key: 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
      region: us-west-2
      app: tournament-services
      env: tournamentServices-env
      bucket_name: us-west-2.elasticbeanstalk.com
      zip_file: 'build/libs/tournament-services-0.1.0-SNAPSHOT.war'