dist: trusty
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sudo psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'sabha123'"
  - sudo psql -U postgres -c 'CREATE DATABASE tournaments'
language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - TERM=dumb
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=swarooprajg/tourpark-postgres
script:
  - docker build -t $REPO:$COMMIT docker
after_success:
  - docker login -e="swarooprajg@gmail.com" -u="swarooprajg" -p="TourPark"
  - docker images
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker images
  - docker push $REPO
