dist: trusty
sudo: required
services:
  - postgresql
addons:
    postgresql: "9.6"
language:
    java
jdk:
    - oraclejdk8
env:
  matrix:
    - TERM=dumb
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - POSTGRESREPO=swarooprajg/tourpark-postgres
    - SERVICESREPO=swarooprajg/tournament-services
script:
  - gradle clean build
after_success:
  - gradle cobertura coveralls
  - echo $COMMIT
  - docker images
  - gradle buildDocker
  - docker login -e="swarooprajg@gmail.com" -u="swarooprajg" -p="TourPark"
  - docker build -t $POSTGRESREPO:latest docker/postgres
  - docker tag tournament-services:latest $SERVICESREPO:latest
  - docker images
  - docker push $POSTGRESREPO
  - docker push $SERVICESREPO
